version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scrapperdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  spring-app:
    build:
      context: .   # Path to your backend project
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - mysql
    environment:
      - spring.application.name=job-scrapper
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/scrapperdb
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true

    ports:
      - "8080:8080"
    networks:
      - app-network

  react-app:
    build:
      context: ./job-scrapper-frontend   # Path to your backend project
      dockerfile: Dockerfile
    container_name: react-app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - spring-app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: